
namespace WM_SalesOrderSplit.Prama
{
    class Stringia
    {
        public const string sWM_SalesOrderSplit = "" +
            "<?xml version=\"1.0\" encoding=\"UTF-16\"?>" +
            "<Application>" +
              "<forms>" +
                "<action type=\"add\">" +
                  "<form appformnumber=\"WMSalesOrderSplit\" FormType=\"WMSalesOrderSplit\" type=\"0\" BorderStyle=\"0\" uid=\"\" title=\"Ειδικός Διαχωρισμός Παραγγελιών\" visible=\"0\" default_button=\"NextBtn\" pane=\"1\" color=\"0\" left=\"0\" top=\"0\" width=\"983\" height=\"650\" client_width=\"\" client_height=\"\" AutoManaged=\"0\" SupportedModes=\"15\" ObjectType=\"\" mode=\"1\">" +
                    "<datasources>" +
                      "<DataTables>" +
                        "<DataTable Uid=\"ResultDT\">" +
                          "<Columns />" +
                        "</DataTable>" +
                        "<DataTable Uid=\"AddResDT\">" +
                          "<Columns>" +
                            "<Column Type=\"1\" MaxLength=\"100\" Uid=\"AddRes\" />" +
                            "<Column Type=\"1\" MaxLength=\"100\" Uid=\"OriginType\" />" +
                            "<Column Type=\"2\" MaxLength=\"0\" Uid=\"OrgDocNtr\" />" +
                            "<Column Type=\"1\" MaxLength=\"100\" Uid=\"OrgObjTp\" />" +
                            "<Column Type=\"1\" MaxLength=\"100\" Uid=\"TargetType\" />" +
                            "<Column Type=\"2\" MaxLength=\"0\" Uid=\"TrgDocNtry\" />" +
                            "<Column Type=\"1\" MaxLength=\"100\" Uid=\"TrgObjTp\" />" +
                            "<Column Type=\"1\" MaxLength=\"254\" Uid=\"ItmType\" />" +
                            "<Column Type=\"2\" MaxLength=\"0\" Uid=\"SapErrCode\" />" +
                            "<Column Type=\"3\" MaxLength=\"0\" Uid=\"SapErrMsg\" />" +
                          "</Columns>" +
                        "</DataTable>" +
                        "<DataTable Uid=\"SeriesFrDT\">" +
                          "<Columns />" +
                        "</DataTable>" +
                      "</DataTables>" +
                      "<dbdatasources>" +
                        "<action type=\"add\">" +
                          "<datasource tablename=\"OUSR\" />" +
                          "<datasource tablename=\"OCRD\" />" +
                        "</action>" +
                      "</dbdatasources>" +
                      "<userdatasources>" +
                        "<action type=\"add\">" +
                          "<datasource type=\"10\" size=\"0\" uid=\"DocDateFr\" />" +
                          "<datasource type=\"10\" size=\"0\" uid=\"DocDateTo\" />" +
                          "<datasource type=\"10\" size=\"0\" uid=\"TaxDateTo\" />" +
                          "<datasource type=\"10\" size=\"0\" uid=\"TaxDateFr\" />" +
                          "<datasource type=\"8\" size=\"0\" uid=\"SeriesTo\" />" +
                          "<datasource type=\"10\" size=\"0\" uid=\"TrgtDocDat\" />" +
                          "<datasource type=\"9\" size=\"1\" uid=\"SlctAllPn1\" />" +
                          "<datasource type=\"8\" size=\"0\" uid=\"SubCatDS\" />" +
                          "<datasource type=\"10\" size=\"0\" uid=\"DocDateDS\" />" +
                          "<datasource type=\"9\" size=\"1\" uid=\"ElleipsiDS\" />" +
                          "<datasource type=\"8\" size=\"0\" uid=\"CommentsDS\" />" +
                        "</action>" +
                      "</userdatasources>" +
                    "</datasources>" +
                    "<Menus />" +
                    "<items>" +
                      "<action type=\"add\">" +
                        "<item top=\"580\" left=\"760\" width=\"90\" height=\"20\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"4\" visible=\"1\" uid=\"NextBtn\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Επόμενο\" />" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"1\" text_style=\"\" top=\"60\" left=\"215\" width=\"95\" height=\"14\" AffectsFormMode=\"1\" description=\"Document Date From\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"1\" uid=\"DocDateEDF\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"DocDateFr\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"2\" text_style=\"\" top=\"60\" left=\"355\" width=\"95\" height=\"14\" AffectsFormMode=\"1\" description=\"Document Date To\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"1\" uid=\"DocDateEDT\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"DocDateTo\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"580\" left=\"760\" width=\"90\" height=\"20\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"2\" to_pane=\"3\" linkto=\"\" right_just=\"0\" type=\"4\" visible=\"1\" uid=\"BackBtn\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Πίσω\" />" +
                        "</item>" +
                        "<item top=\"580\" left=\"15\" width=\"90\" height=\"20\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"0\" to_pane=\"0\" linkto=\"\" right_just=\"0\" type=\"4\" visible=\"1\" uid=\"2\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Cancel\" />" +
                        "</item>" +
                        "<item top=\"580\" left=\"860\" width=\"90\" height=\"20\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"1\" enabled=\"1\" from_pane=\"2\" to_pane=\"2\" linkto=\"\" right_just=\"0\" type=\"4\" visible=\"1\" uid=\"ExecBtn\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Εκτέλεση\" />" +
                        "</item>" +
                        "<item top=\"60\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"DocDateEDF\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"DocDateSTF\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Ημ/νία Καταχώρησης από:\" />" +
                        "</item>" +
                        "<item top=\"60\" left=\"320\" width=\"30\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"DocDateEDT\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"DocDateSTT\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"έως:\" />" +
                        "</item>" +
                        "<item top=\"10\" left=\"15\" width=\"355\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_12\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Επιλογή Κριτηρίων\" />" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"0\" text_style=\"\" top=\"35\" left=\"215\" width=\"95\" height=\"14\" AffectsFormMode=\"1\" description=\"CardCode\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"1\" uid=\"CardCodeED\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"CardCode\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"OCRDCFL\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"OCRD\" alias=\"CardCode\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"35\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"CardCodeED\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"WhsCodeST\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Συναλλασσόμενος:\" />" +
                        "</item>" +
                        "<item top=\"30\" left=\"15\" width=\"950\" height=\"535\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"2\" to_pane=\"2\" linkto=\"\" right_just=\"0\" type=\"128\" visible=\"1\" uid=\"ResultsGRD\" IsAutoGenerated=\"0\">" +
                          "<specific CollapseLevel=\"0\" DataTable=\"ResultDT\" SelectionMode=\"2\">" +
                            "<RowHeaders Width=\"20\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"580\" left=\"110\" width=\"90\" height=\"20\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"2\" to_pane=\"2\" linkto=\"\" right_just=\"0\" type=\"4\" visible=\"1\" uid=\"SelectBTN\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Επιλογή Όλων\" />" +
                        "</item>" +
                        "<item top=\"580\" left=\"205\" width=\"90\" height=\"20\" AffectsFormMode=\"1\" description=\"Ανανέωση της λίστας και αποεπιλογή επιλεγμένων Παραστατικών.\" disp_desc=\"1\" enabled=\"1\" from_pane=\"2\" to_pane=\"2\" linkto=\"\" right_just=\"0\" type=\"4\" visible=\"1\" uid=\"RefreshBT\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Ανανέωση\" />" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"4\" text_style=\"\" top=\"85\" left=\"355\" width=\"95\" height=\"14\" AffectsFormMode=\"1\" description=\"Tax Date To\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"1\" uid=\"TaxDateEDT\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"TaxDateTo\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"3\" text_style=\"\" top=\"85\" left=\"215\" width=\"95\" height=\"14\" AffectsFormMode=\"1\" description=\"Tax Date From\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"1\" uid=\"TaxDateEDF\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"TaxDateFr\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"35\" left=\"320\" width=\"580\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"CardNameST\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"\" />" +
                        "</item>" +
                        "<item top=\"85\" left=\"320\" width=\"30\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"TaxDateEDT\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_3\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"έως:\" />" +
                        "</item>" +
                        "<item top=\"85\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"TaxDateEDF\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_2\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Ημ/νία Παραστατικού από:\" />" +
                        "</item>" +
                        "<item top=\"500\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_5\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Σειρά Στόχου:\" />" +
                        "</item>" +
                        "<item tab_order=\"7\" top=\"500\" left=\"215\" width=\"130\" height=\"14\" AffectsFormMode=\"1\" description=\"Series To\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"113\" visible=\"1\" uid=\"SeriesTo\" IsAutoGenerated=\"0\">" +
                          "<specific>" +
                            "<ValidValues>" +
                              "<action type=\"add\" />" +
                            "</ValidValues>" +
                            "<databind databound=\"1\" table=\"\" alias=\"SeriesTo\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"5\" text_style=\"\" top=\"140\" left=\"180\" width=\"120\" height=\"14\" AffectsFormMode=\"1\" description=\"Document Date From\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"0\" uid=\"TrgtDocDat\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"TrgtDocDat\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"140\" left=\"15\" width=\"150\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"TrgtDocDat\" right_just=\"0\" type=\"8\" visible=\"0\" uid=\"Item_20\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Ημ/νία Έκδοσης Στόχου:\" />" +
                        "</item>" +
                        "<item top=\"10\" left=\"15\" width=\"355\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"2\" to_pane=\"2\" linkto=\"\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_0\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Επιλογή Παραστατικών\" />" +
                        "</item>" +
                        "<item top=\"30\" left=\"15\" width=\"950\" height=\"535\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"3\" to_pane=\"3\" linkto=\"\" right_just=\"0\" type=\"128\" visible=\"1\" uid=\"AddResGRD\" IsAutoGenerated=\"0\">" +
                          "<specific CollapseLevel=\"0\" DataTable=\"AddResDT\" SelectionMode=\"0\">" +
                            "<RowHeaders Width=\"20\" />" +
                            "<GridColumns>" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"AddRes\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"AddRes\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"OriginType\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"OriginType\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"OrgDocNtr\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"OrgDocNtr\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"OrgObjTp\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"OrgObjTp\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"TargetType\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"TargetType\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"TrgDocNtry\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"TrgDocNtry\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"TrgObjTp\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"TrgObjTp\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"ItmType\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"ItmType\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"SapErrCode\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"SapErrCode\" sortable=\"0\" />" +
                              "<GridColumn BackColor=\"-1\" ChooseFromListIsAutoFill=\"0\" TextStyle=\"0\" Visible=\"1\" AffectsFormMode=\"1\" Title=\"SapErrMsg\" Width=\"50\" Editable=\"0\" Type=\"16\" RightJustified=\"0\" UniqueID=\"SapErrMsg\" sortable=\"0\" />" +
                            "</GridColumns>" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"8\" left=\"15\" width=\"408\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"3\" to_pane=\"3\" linkto=\"\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_6\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Αποτελέσματα\" />" +
                        "</item>" +
                        "<item top=\"135\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"SeriesFrGr\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_1\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Σειρά Βάσης:\" />" +
                        "</item>" +
                        "<item top=\"135\" left=\"215\" width=\"570\" height=\"165\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"128\" visible=\"1\" uid=\"SeriesFrGr\" IsAutoGenerated=\"0\">" +
                          "<specific CollapseLevel=\"0\" DataTable=\"SeriesFrDT\" SelectionMode=\"0\">" +
                            "<RowHeaders Width=\"20\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"110\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"SubCatCB\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_7\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Oικογένεια πελάτη:\" />" +
                        "</item>" +
                        "<item tab_order=\"5\" top=\"110\" left=\"215\" width=\"235\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"113\" visible=\"1\" uid=\"SubCatCB\" IsAutoGenerated=\"0\">" +
                          "<specific>" +
                            "<ValidValues>" +
                              "<action type=\"add\" />" +
                            "</ValidValues>" +
                            "<databind databound=\"1\" table=\"\" alias=\"SubCatDS\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"525\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"DocDateED\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_9\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Ημ. Καταχώρησης Στόχου:\" />" +
                        "</item>" +
                        "<item top=\"60\" left=\"460\" width=\"128\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"121\" visible=\"1\" uid=\"ElleipsiCB\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Είδη σε έλλειψη\" val_on=\"Y\" val_off=\"N\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"ElleipsiDS\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item backcolor=\"-1\" font_size=\"-1\" forecolor=\"-1\" tab_order=\"8\" text_style=\"\" top=\"525\" left=\"215\" width=\"95\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"1\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"16\" visible=\"1\" uid=\"DocDateED\" IsAutoGenerated=\"0\">" +
                          "<specific ChooseFromListAlias=\"\" ChooseFromListIsAutoFill=\"0\" ChooseFromListUID=\"\" IsPassword=\"0\" supp_zeros=\"0\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"DocDateDS\" />" +
                          "</specific>" +
                        "</item>" +
                        "<item top=\"310\" left=\"15\" width=\"190\" height=\"14\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"CommentsED\" right_just=\"0\" type=\"8\" visible=\"1\" uid=\"Item_4\" IsAutoGenerated=\"0\">" +
                          "<specific caption=\"Σχόλια:\" />" +
                        "</item>" +
                        "<item font_size=\"-1\" supp_zeros=\"0\" tab_order=\"6\" text_style=\"\" top=\"310\" left=\"215\" width=\"355\" height=\"70\" AffectsFormMode=\"1\" description=\"\" disp_desc=\"0\" enabled=\"1\" from_pane=\"1\" to_pane=\"1\" linkto=\"\" right_just=\"0\" type=\"118\" visible=\"1\" uid=\"CommentsED\" IsAutoGenerated=\"0\">" +
                          "<specific ScrollBars=\"2\">" +
                            "<databind databound=\"1\" table=\"\" alias=\"CommentsDS\" />" +
                          "</specific>" +
                        "</item>" +
                      "</action>" +
                    "</items>" +
                    "<ChooseFromListCollection>" +
                      "<action type=\"add\">" +
                        "<ChooseFromList UniqueID=\"-1\" ObjectType=\"-1\" MultiSelection=\"0\" IsSystem=\"1\" />" +
                        "<ChooseFromList UniqueID=\"OCRDCFL\" ObjectType=\"2\" MultiSelection=\"0\" IsSystem=\"0\" />" +
                      "</action>" +
                    "</ChooseFromListCollection>" +
                    "<DataBrowser BrowseBy=\"\" />" +
                    "<Settings MatrixUID=\"\" Enabled=\"0\" EnableRowFormat=\"0\" />" +
                  "</form>" +
                "</action>" +
              "</forms>" +
            "</Application>",

            sExecSQL = "SELECT V.*, IFNULL(G.\"ItmsGrpNam\", '') \"ItmsGrpNam\" FROM " +
                       "    (SELECT Q.\"DocEntry\", " +
                       "        Q.\"CardCode\", " +
                       "        Q.\"DocDate\", " +
                       "        Q.\"TaxDate\", " +
                       "        Q.\"NumAtCard\", " +
                       "        Q1.\"VisOrder\", " +
                       "        Q1.\"LineNum\", " +
                       "        Q1.\"ItemCode\", " +
                       "        Q1.\"ObjType\", " +
                       //"        --CASE I.\"QryGroup1\" WHEN 'Y' THEN 1 ELSE 2 END PROPERTIES " +
                       "        CASE I.\"QryGroup1\" WHEN 'Y' THEN 1 " +
                       "        ELSE CASE I.\"QryGroup2\" WHEN 'Y' THEN 2 ELSE -1 END END PROPERTIES " +
                       "    FROM QUT1 Q1 " +
                       "    INNER JOIN OQUT Q ON Q.\"DocEntry\" = Q1.\"DocEntry\" " +
                       "    INNER JOIN OITM I ON I.\"ItemCode\" = Q1.\"ItemCode\" " +
                       "    LEFT JOIN ( " +
                       "    SELECT DISTINCT R1.\"BaseEntry\", R1.\"BaseLine\", R1.\"DocEntry\" " +
                       "        FROM RDR1 R1 " +
                       "        INNER JOIN ORDR R ON R.\"DocEntry\" = R1.\"DocEntry\" " +
                       "        WHERE R1.\"BaseType\" = '23' " +
                       "          AND R.CANCELED = 'N' " +
                       "        ) CNL ON CNL.\"BaseEntry\" = Q1.\"DocEntry\" AND CNL.\"BaseLine\" = Q1.\"LineNum\" " +
                       "    WHERE I.\"QryGroup4\" = 'N' " +
                       //"        --AND (I.\"QryGroup1\" = 'Y' OR I.\"QryGroup2\" = 'Y') " +
                       "        AND Q.\"DocEntry\" IN ({0}) " +
                       "        AND CNL.\"DocEntry\" IS NULL " +
                       "        AND LEFT(I.\"ItemCode\", 3) != 'ΠΦΣ' " +
                       "    UNION ALL " +
                       "        SELECT 99999999, " +
                       "            NULL, " +
                       "            CURRENT_DATE, " +
                       "            CURRENT_DATE, " +
                       "            NULL, " +
                       "            99999999, " +
                       "            99999999, " +
                       "            NULL, " +
                       "            NULL, " +
                       "            99999999 " +
                       "        FROM DUMMY ) V " +
                       "        LEFT JOIN OITG G ON G.\"ItmsTypCod\" = V.PROPERTIES " +
                       "    ORDER BY 1 ASC, 9 ",

            sNextSQL = "SELECT 'N' \"Check\", " +
                           "         Q.\"DocNum\", " +
                           "         Q.\"DocEntry\", " +
                           "         Q.\"CardCode\", " +
                           "         Q.\"CardName\", " +
                           "         C.\"LicTradNum\", " +
                           "         C.\"U_TKA_CustSubCategory\", " +
                           "         Q.\"DocDate\", " +
                           "         Q.\"TaxDate\", " +
                           //"         '{0}' \"TargetDate\", " +
                           "         Q.\"DocTotal\", " +
                           "         CASE IFNULL(Q.\"U_TKA_WebOrder\", '') WHEN '' THEN Q.\"NumAtCard\" ELSE Q.\"U_TKA_WebOrder\" END \"NumAtCard\", " +
                           "         TO_VARCHAR(Q.\"U_TKA_BPComments\") \"U_TKA_BPComments\", " +
                           "         N1.\"SeriesName\", " +
                           "         IFNULL(A.A, 0) ZERO_IS_INVALID " +
                           "     FROM QUT1 Q1 " +
                           "     INNER JOIN OQUT Q ON Q.\"DocEntry\" = Q1.\"DocEntry\" AND Q.CANCELED = 'N' " +
                           "     INNER JOIN OITM I ON I.\"ItemCode\" = Q1.\"ItemCode\" " +
                           "     INNER JOIN OCRD C ON C.\"CardCode\" = Q.\"CardCode\" " +
                           "     INNER JOIN NNM1 N1 ON N1.\"Series\" = Q.\"Series\" " +
                           "     LEFT JOIN \"@TKA_SUBCATEGORY\" SC ON C.\"U_TKA_CustSubCategory\" = SC.\"Name\" " +
                           "     LEFT JOIN ( " +
                           "     SELECT DISTINCT R1.\"BaseEntry\", R1.\"BaseLine\", R1.\"DocEntry\" " +
                           "        FROM RDR1 R1 " +
                           "        INNER JOIN ORDR R ON R.\"DocEntry\" = R1.\"DocEntry\" " +
                           "        WHERE R1.\"BaseType\" = '23' " +
                           "          AND R.CANCELED = 'N' " +
                           "        ) CNL ON CNL.\"BaseEntry\" = Q1.\"DocEntry\" AND CNL.\"BaseLine\" = Q1.\"LineNum\" " +
                           "     LEFT JOIN " +
                           "         (SELECT COUNT(Q1.\"DocEntry\") A, Q1.\"DocEntry\" FROM QUT1 Q1 INNER JOIN OITM I ON I.\"ItemCode\" = Q1.\"ItemCode\" " +
                           "         LEFT JOIN(SELECT DISTINCT R1.\"BaseEntry\", R1.\"BaseLine\", R1.\"DocEntry\" " +
                           "         FROM RDR1 R1 " +
                           "         INNER JOIN ORDR R ON R.\"DocEntry\" = R1.\"DocEntry\"  " +
                           "         WHERE R1.\"BaseType\" = '23' AND R.CANCELED = 'N') CNL ON CNL.\"BaseEntry\" = Q1.\"DocEntry\" AND CNL.\"BaseLine\" = Q1.\"LineNum\" " +
                           "         WHERE I.\"QryGroup4\" = 'N' " +
                           "         AND CNL.\"DocEntry\" IS NULL " +
                           "         AND LEFT(I.\"ItemCode\", 3) != 'ΠΦΣ' " +
                           "         GROUP BY Q1.\"DocEntry\") A ON A.\"DocEntry\" = Q1.\"DocEntry\" " +
                           "     WHERE 1=1 " +
                           "         AND (I.\"QryGroup4\" = 'N' OR 'Y' = '{0}') " +
                           "         AND LEFT(I.\"ItemCode\", 3) != 'ΠΦΣ' " +
                           "         AND CNL.\"DocEntry\" IS NULL " +
                           "          ";
            //"         AND (I.\"QryGroup1\" = 'Y' OR I.\"QryGroup2\" = 'Y') ";
    }
}
